# Generated by Django 4.1.3 on 2023-01-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('nature', models.CharField(max_length=255)),
                ('sinal', models.CharField(max_length=255)),
            ],
        ),
    ]
